### ISSUE TITLE
Nothing happens when "BlueButton Download My Data" button is clicked

### ISSUE THREAD

**Issue by au2** [amida-tech/dre-frontend#15]

**Comment by UglyEugen** [comment]
@kachok , am I right assuming that we should generate XML ourselves based on the full FHIR record, alike we did with Print function?

**Comment by igiware** [comment]
@kachok, 
because of Blue Button originally generating data in same xml-format as upload file API using on dre-service side, it's logical to assume, that data will be generated on dre-service side and passed to the dre-frontend using API call. 
If it's incorrect than we have to implement data converter FHIR-resources to BlueButton xml on frontend side.

**Comment by au2** [comment]
Please use /api/v1/mhr.  A preliminary version is implemented in DRE-services@ddeb08c01621575adac7f978f198660af29baafb.
