### ISSUE TITLE
Attempt to load file from "My Files" list returns a resource in JSON format

### ISSUE THREAD

**Issue by chaldon** [amida-tech/dre-frontend#26]
, not a content of file as user would expect.

**Comment by igiware** [comment]
http://dre.ntrlab.ru:8080/fhir/baseDstu2/DocumentReference/111795?_format=json returns 

{
    "resourceType":"DocumentReference",
    "id":"111795",
...
    "content":[
        {
            "attachment":{
                "contentType":"text/xml",
                "url":"http://localhost:8080/fhir/baseDstu2/Binary/111793/_history/1",
                "title":"bluebutton-primary.xml"
            }
        }
    ]
}

but
"http://dre.ntrlab.ru:8080/fhir/baseDstu2/Binary/111793/_history/1?_format=json"

returns 
{
    "resourceType":"Binary",
    "id":"111793",
    "meta":{
        "versionId":"1",
        "lastUpdated":"2015-11-03T10:23:52.733+03:00"
    },
    "contentType":"application/json",
"content":"<base64_encoded content>"
}

decoded content is another Binary resource {"resourceType":"Binary","contentType":"text/xml","content":""} which is original file

Assume, the reason is in double encoding Binary, while uploaded file was processed

**Comment by chaldon** [comment]
Yep, looks like backend logic changed a bit - I'll try to fix on DRE-services level.

**Comment by chaldon** [comment]
Fixed for new uploads
