### ISSUE TITLE
Review Merges checkboxes/formatting

### ISSUE THREAD

**Issue by kachok** [amida-tech/dre-frontend#53]
When checkboxes used and data copied from left record to right record, formatting is not applied to "updated" part (e.g. date formatting or code formattng)

**Comment by igiware** [comment]
can you provide examples, please?

**Comment by UglyEugen** [comment]
maybe a browser-related issue?

**Comment by igiware** [comment]
checked in Firefox & Chrome on new and test users: can't reproduce

**Comment by kachok** [comment]
<img width="1182" alt="screen shot 2015-12-09 at 11 54 32 pm" src="https://cloud.githubusercontent.com/assets/139923/11707285/61657f36-9ed0-11e5-9eab-b3ed4ea591c8.png">

**Comment by igiware** [comment]
i see
that's because change(s) is inside coding structure
original data:
coding: [
    {
         display: 'Naursea',
         code: '422587007',
         system: 'http://....'
    }
]
matched data:
coding: [
    {
         display: 'Naursea'
    }
]

coding with changes inside can be wrapped into one line, but there few problems:
- how it will looks at left-side when 'no data' or rigth-side when 'new data'?
- when change will be E-kind (changed two or three of 'code', 'display' ,'system') what changes will be controlled with checkbox?

**Comment by kachok** [comment]
In this case check box should operate on entire coding element (e.g. display will replace display/code/system) we should show them as different (not a "no data")

**Comment by kachok** [comment]
Let's keep current functionality and translate System to human readable e.g. URIs -> RxNORM/SNOMED etc

**Comment by igiware** [comment]
updated with efda7e348456f18844a951ddd12e647343387786

**Comment by igiware** [comment]
updated in dev branch with c08dfba228eca0ea4dc6c0e9291b6dd6c195366c
