### ISSUE TITLE
When "save update" performed on matches update provenance

### ISSUE THREAD

**Issue by kachok** [amida-tech/dre-frontend#55]
add new record to extensions: "Patient merged" with timestamp and no source.

**Comment by mhiner** [comment]
One thing to note is that the current source presentation fails if there is no reference value since the reference node is undefined.   If I put in a bogus reference value of "NA" then it presents some of the history but fails when it tries to lookup "NA" from hapi.

I will look into this come more one I finish adding the history.

**Comment by kachok** [comment]
@igiware can we add handling of Sources for empty or "NA" value?

**Comment by igiware** [comment]
sure, we already handling empty reference for 'Patient Entered' source extension, (if i understood you correcly)
